name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when main branch is updated

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history required

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm ci
      - run: npm run build

      - uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}  # PAT with repo contents RW
          publish_dir: ./build
          force_orphan: true
